name: "Frogbot Scan Pull Request"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - uses: jfrog/frogbot@v3
        with:
          oidc-provider-name: kamal-github
          oidc-audience: https://hts2.jfrog.io
        env:
          JF_URL: https://hts2.jfrog.io
          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
          JF_INSTALL_DEPS_CMD: "npm install"
